### ISSUE TITLE
signalr握手协议

### ISSUE THREAD

**Issue by LFeYls** [liangshiw/SignalRMiniProgram-Client#11]
请问一下是否支持使用SignalR的禁用协议，不经过握手协议进行直接连接
我遇到的问题是，后端api进行分布式部署，如果握手协议和之后的连接不是统一服务器的话，会导致后边的连接无法建立

**Comment by realLiangshiwei** [comment]
建议你使用signalr 底板。https://docs.microsoft.com/en-us/aspnet/signalr/overview/performance/scaleout-in-signalr

**Comment by LFeYls** [comment]
已经使用了signalR的地板，不过这个底板的作用我理解的是只能在发送消息的时候Redis通知持有这个连接的服务器发送。
但是小程序链接SignalR：
第一步要先通过握手协议获取到连接信息(这个信息应该只保存在了握手协议通过的这台服务器)，
第二步才建立连接。这两不就有可能导致不能连接到同意服务器从而导致真正建立连接的时候会导致失败，当然，这个也不是您这个项目的问题，只是我看Web中使用signalr的时候可以禁用协商，相当于只进行第二部直接连接，如果小程序这边可以支持的话，服务器端其实可以用负载均衡模式而不需要使用iphash的模式(这种模式可能会导致部分服务器压力比较大)，如果可以禁用协议的话，我觉得就可以解决这个问题了。
总之，谢谢大佬开源的这个项目

**Comment by realLiangshiwei** [comment]
> 只是我看Web中使用signalr的时候可以禁用协商

有链接提供一下吗

**Comment by LFeYls** [comment]
https://www.bilibili.com/video/BV1pK41137He?p=158
