### ISSUE TITLE
这是能用net core3.1 里面signalR 配合用的吧？

### ISSUE THREAD

**Issue by bbhxwl** [liangshiw/SignalRMiniProgram-Client#12]
我看项目有几年没更新，不知道还适合新版的么

**Comment by realLiangshiwei** [comment]
~~不能 ，有时间我考虑写一个适用于 aspnet core SignalR的版本~~

**Comment by bbhxwl** [comment]
好吧，我看项目介绍写的【signalr core 小程序版客户端js】，我以为可以。

**Comment by realLiangshiwei** [comment]
Sorry, 我记错了，这个就是适用于 aspnet core SignalR的版本
