### ISSUE TITLE
请教下小程序如果退出再回来，应该怎么处理signalR的重连机制

### ISSUE THREAD

**Issue by bbhxwl** [liangshiw/SignalRMiniProgram-Client#13]
不知道退出小程序再回来，signalR 是不是会断开。有自动重连的机制么。

**Comment by realLiangshiwei** [comment]
如果小程序能后台的话会保活，没有的话就会断开，你可以处理一下hub的断开事件和连接事件，自己做一下重连后的逻辑。

**Comment by realLiangshiwei** [comment]
js 也有关闭的事件，你可以订阅一下。 
![image](https://user-images.githubusercontent.com/16813853/154185504-c78a56c6-c8e5-4b46-8374-3a354b9117ec.png)
