### ISSUE TITLE
请问一下这里为什么要加  

### ISSUE THREAD

**Issue by duuliy** [liangshiw/SignalRMiniProgram-Client#2]
加这个不返回消息，加了返回的是错误信息，而不是发送信息

**Comment by liangshiw** [comment]
多个消息用一个数据包发送的时候用做区分

**Comment by realLiangshiwei** [comment]
> 加这个不返回消息，加了返回的是错误信息，而不是发送信息

多个消息用一个数据包发送的时候用�做区分,你可以用最新的js，我又改了一些代码
