### ISSUE TITLE
请问小程序端onClose里怎么判断是客户端关闭连接还是服务器断掉了连接

### ISSUE THREAD

**Issue by ssgnoob** [liangshiw/SignalRMiniProgram-Client#3]
请问小程序端onClose里怎么判断是客户端关闭连接还是服务器断掉了连接。另外服务端除了调用客户端关闭连接方法，还能主动断开某一个连接嘛，我查了好久的api都没有找到

**Comment by compass-yan** [comment]
在onClose里打个断点看下状态码，PS：你的服务端用的是什么

**Comment by ssgnoob** [comment]
> 在onClose里打个断点看下状态码，PS：你的服务端用的是什么

我现在就知道两个状态码，1000是小程序端断开连接  1006是我直接本地停止代码调试，我很想知道有没有相关的文档详细介绍下这个，我服务端用的和这个作者的一样 Microsoft.AspNetCore.SignalR

**Comment by compass-yan** [comment]
可以到官方文档上看一下或者F12看下源码，我觉得Abort可能是你想要的。
![image](https://user-images.githubusercontent.com/22750919/46579544-c8315d80-ca46-11e8-9252-c85c0d45d47d.png)

**Comment by realLiangshiwei** [comment]
你可以参考websocket的状态码
