### ISSUE TITLE
如何使用 asp.net core 的认证，在 hub 里面获得 Context.User

### ISSUE THREAD

**Issue by StarkShang** [liangshiw/SignalRMiniProgram-Client#4]
如何将自己的 cookie 添加到 connection 里面？
我尝试修改了 start 方法， 将 cookie 添加到 httphead 里面，但是这种方法经常不起作用。
而且在 hub 里面 Context.User 是 null

**Comment by realLiangshiwei** [comment]
https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-2.1 你可以参阅官方文档。
我认为你应该分享此问题的更多细节
