### ISSUE TITLE
有个东西叫uniapp,不晓得能不能改成他能用的啊..现在就卡这了...

### ISSUE THREAD

**Issue by tinuxer** [liangshiw/SignalRMiniProgram-Client#5]
有个东西叫uniapp,不晓得能不能改成他能用的啊..现在就卡这了...想用这个,,可惜卡在singnalr了

https://uniapp.dcloud.io/api/request/websocket

**Comment by realLiangshiwei** [comment]
都是WebSocket协议，你可以参照我的代码改一下

**Comment by tinuxer** [comment]
我正在看..我感觉格式都是一样的..试试看吧

**Comment by tinuxer** [comment]
data: JSON.stringify(data) + "", //   这是什么东西?

**Comment by realLiangshiwei** [comment]
消息分割的。
