### ISSUE TITLE
socket连接无法关闭，close无效

### ISSUE THREAD

**Issue by 1458882634** [liangshiw/SignalRMiniProgram-Client#9]
socket连接无法关闭，close无效，最终导致小程序报出最多只能开启两个websocket。

**Comment by realLiangshiwei** [comment]
提供复现步骤？

**Comment by 1458882634** [comment]
现在倒是可以了，自己写的时候用的是this.connection.close()无法关闭，改成this.close()就可以了，应该是我同事搞错方法的主体了。

**Comment by realLiangshiwei** [comment]
OK
